modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="testing"
version="1.0.0"
displayName="testing"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="lloyd, MCreator"

[[dependencies.testing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



